### ISSUE TITLE
Stable Diffusion AWS extension API: wrong parameter

### ISSUE THREAD

**Issue by Shellmode** [awslabs/stable-diffusion-aws-extension#102]
### Describe the issue

Body parameter "stable_diffusion_model " of /api/inference/run-sagemaker-inference should be a string not list

```
{
  "stable_diffusion_model": ["v1-5-pruned-emaonly.safetensors"],
  "sagemaker_endpoint": "infer-endpoint-cb821ea",
  "task_type": "txt2img",
  "prompt": "a cute panda",
  "denoising_strength": 0.75
}
```

will get the error 'failure', 'error': "error info 'list' object has no attribute 'split'

the correct parameter should be
```
{
  "stable_diffusion_model": "v1-5-pruned-emaonly.safetensors",
  "sagemaker_endpoint": "infer-endpoint-cb821ea",
  "task_type": "txt2img",
  "prompt": "a cute panda",
  "denoising_strength": 0.75
}
```

### Links

https://awslabs.github.io/stable-diffusion-aws-extension/en/developer-guide/api/

**Comment by guming3d** [comment]
Thanks for pointing out, will fix that next week.
