### ISSUE TITLE
WebUI: Cannot configure Amazon Sagemaker API

### ISSUE THREAD

**Issue by Shellmode** [awslabs/stable-diffusion-aws-extension#135]
### Describe the bug

Cannot update API Url and API Token after installing Stable Diffusion WebUI on EC2(Ubuntu 20.04.1)

![Screenshot 2023-08-11 at 00 41 05](https://github.com/awslabs/stable-diffusion-aws-extension/assets/3354682/d2176944-4d12-4276-a20b-0f2ab6e9a209)

I just installed stable diffusion webui on EC2 by [this doc](https://github.com/awslabs/stable-diffusion-aws-extension/blob/main/docs/Environment-Preconfiguration.md) Option 2, and configured a nginx as proxy in front of the webui process

```
location / {
                proxy_pass http://127.0.0.1:7860;
                #try_files $uri $uri/ =404;
        }
```

When I access webui from my browser, I got error at the API Url & API Token tab, therefore I cannot configure my API for the extension.

### Expected Behavior

Be able to configure API for the extension

### Current Behavior

![Screenshot 2023-08-11 at 00 41 05](https://github.com/awslabs/stable-diffusion-aws-extension/assets/3354682/ac159987-fd6d-4864-9ebd-ef417226ea15)

Cannot Configure API for the extension.

### Reproduction Steps

1. Install the stable-diffusion-webui and extension with option2 from  [this doc](https://github.com/awslabs/stable-diffusion-aws-extension/blob/main/docs/Environment-Preconfiguration.md)
2. Install nginx and configured as a proxy
```
location / {
                proxy_pass http://127.0.0.1:7860;
                #try_files $uri $uri/ =404;
        }
```
3. Access the nginx

### Solution Version

not related

**Comment by yike5460** [comment]
will you able to connect to the http://${MyEIP.PublicIp}:7860 directly instead of proxy?

**Comment by alvindaiyan** [comment]
@Shellmode Have you solved the problem?
