### ISSUE TITLE
Deployment step: no place to choose EC2 key pair

### ISSUE THREAD

**Issue by Shellmode** [awslabs/stable-diffusion-aws-extension#136]
### Describe the issue

Deployment steps
Step 1: Deploy Stable Diffusion WebUI (Linux).

5. On the Specify stack details page, type a stack name in the Stack name box. Choose an EC2 instance key pair, then choose Next.

There is no EC2 instance key pair to choose from [this cloudformation stack](https://raw.githubusercontent.com/awslabs/stable-diffusion-aws-extension/main/workshop/ec2.yaml)

### Links

https://awslabs.github.io/stable-diffusion-aws-extension/en/deployment/deployment/

**Comment by Shellmode** [comment]
I don't know why comment the KeyName Parameters in the [cloudformation stack](https://raw.githubusercontent.com/awslabs/stable-diffusion-aws-extension/main/workshop/ec2.yaml)

```
AWSTemplateFormatVersion: '2010-09-09'
Description: (SO8032) - Stable-Diffusion AWS Extension WebUI - EC2 Instance
# Parameters:
#   KeyName:
#     Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
#     Type: AWS::EC2::KeyPair::KeyName
#     ConstraintDescription: must be the name of an existing EC2 KeyPair.
...
```

**Comment by yike5460** [comment]
The key pair to for debugging purpose to ssh into EC2, user will login into address provided by CloudFormation output directly.

**Comment by ensean** [comment]
@yike5460 without ssh access, how does the user add models to sd webui and upload it to s3 for Sagemaker's use?

**Comment by ensean** [comment]
Noticed that the new version of UI can upload model from local drive. But I think download model to the webui server and upload it to S3 will be more efficient...

**Comment by Shellmode** [comment]
> Noticed that the new version of UI can upload model from local drive. But I think download model to the webui server and upload it to S3 will be more efficient...

Agree, in most of cases, upload models from EC2 to S3 is faster than from local labtop.
