### ISSUE TITLE
API document: wrong url and parameters

### ISSUE THREAD

**Issue by Shellmode** [awslabs/stable-diffusion-aws-extension#138]
### Describe the issue

There is some mistakes in /inference-api/inference API Code samples
```
import requests
headers = {
  "Content-Type": "application/json",
  "Accept": "application/json",
  'x-api-key': 'API_TOKEN_VALUE'
}
body = {
  "task_type": "txt2img",
  "models": {
    "Stable-diffusion": [
      "v1-5-pruned-emaonly.safetensors"
    ]
  },
  "sagemaker_endpoint": "infer-endpoint-cb821ea",
  "task_type": "txt2img",
  "prompt": "a cute panda",
  "denoising_strength": 0.75
}

r = requests.post("https://<Your API Gateway ID>.execute-api.<Your AWS Account Region>.amazonaws.com/{basePath}/api/inference/run-sagemaker-inference", headers = headers, json = body)

print(r.json())
```

1. the url should be `https://<Your API Gateway ID>.execute-api.<Your AWS Account Region>.amazonaws.com/{basePath}/inference-api/inference` not `api/inference/run-sagemaker-inference`
2. `sagemaker_endpoint` should be `sagemaker_endpoint_name`
3. duplicate `task_type`

It's better to involve document update into your CI/CD.

### Links

https://awslabs.github.io/stable-diffusion-aws-extension/zh/developer-guide/api/

**Comment by NingLu** [comment]
Taking a look

**Comment by NingLu** [comment]
The issue has been fixed, refer to the latest link: https://awslabs.github.io/stable-diffusion-aws-extension/zh/developer-guide/api/#inference-l2-api
