### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by AGronowski** [awslabs/stable-diffusion-aws-extension#177]
### Describe the feature

Thanks for making this extension. Is there any way to make it compatible with the auto1111's progress bar? Or some other way to indicate how much time the generation will take?

### Use Case

Give users more indication on how generation is progressing and how long they should expect to wait

### Solution version used

1.1.0

**Comment by yike5460** [comment]
Currently the inference is asynchronous, requests will send to backend queue and invoke SageMaker, so progress bar can be inaccurate to implement. And estimated inference time depend on the SageMaker endpoint capacity, model, parameters input e.g. batch size, mostly should be around 4-5s  per image.
