### ISSUE TITLE
Sagemaker Endpoint: Memory leak when switch model from SDXL and SD1.5/2.1 back and forth

### ISSUE THREAD

**Issue by Shellmode** [awslabs/stable-diffusion-aws-extension#182]
### Describe the bug

There are some issues describe memory leak when switch models, such as [[Bug]: linux memory leak when switching models](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9323), and there are also some solution to mitigate the problem, like using tcmalloc.

Using tcmalloc seems to have solved the problem, but I recently encountered the memory leak problem again.

### Expected Behavior

No memory leak and no OOM in Sagemaker endpoint.

#### 1. Init a new sagemaker endpoint
<img width="1709" alt="image-20230903005121003" src="https://github.com/awslabs/stable-diffusion-aws-extension/assets/3354682/63c70129-d69f-4a50-9ea1-361d670e8576">

#### 2. Check current sagemaker endpoint memory usage
![image-20230903005343215](https://github.com/awslabs/stable-diffusion-aws-extension/assets/3354682/7d6745a3-e07a-489e-8791-dfcd8c0ee161)

#### 3. Call /inference-api/inference to inference
Call the API_URL with follow parameters one by one (start from 1)
![image](https://github.com/awslabs/stable-diffusion-aws-extension/assets/3354682/f0bad2ba-fdf4-44b3-bd3b-633a76e546c4)

#### 4. Load the first model (SDXL model)
![image](https://github.com/awslabs/stable-diffusion-aws-extension/assets/3354682/ff0abd05-7ecb-4618-a12e-46d74b46cbf8)

we can see memory usage went up
![image-20230903005932916](https://github.com/awslabs/stable-diffusion-aws-extension/assets/3354682/8f1e9b84-0c0a-4dac-9a2b-d2689c00f370)

and the first inference succeeded

#### 5. Load the second model (SD1.5 model)
![image](https://github.com/awslabs/stable-diffusion-aws-extension/assets/3354682/d39aa557-6b72-4c39-99a5-a82c0c5d7923)

and the second inference also succeeded
![image](https://github.com/awslabs/stable-diffusion-aws-extension/assets/3354682/d1e464f7-96d3-4326-ac9e-283e1f730c51)

#### 6. Load the third model (SDXL model)
![image](https://github.com/awslabs/stable-diffusion-aws-extension/assets/3354682/35d78492-91bf-4258-ba34-39eb6970fd66)

and we got OOM
![image](https://github.com/awslabs/stable-diffusion-aws-extension/assets/3354682/43ccc7cf-6b28-4163-8455-1045ae58e0ad)

#### 7. After sagemaker restart
Because there were some requests in Sagemaker async queue, so when sagemaker went back, the endpoint kept switching models back and forth, memory kept going up, and we got another OOM.

![image](https://github.com/awslabs/stable-diffusion-aws-extension/assets/3354682/35a52656-4454-4e61-8eae-8da40e0d3dd2)

### Reproduction Steps

See Current Behavior

### Possible Solution

I'm also trying to figure out a solution.

### Solution Version

commit a4d0de13abb1dd61193100e0e643b8c2ca9f11aa

**Comment by Shellmode** [comment]
I finished another test, which only switch among SD1.5 models, no memory leak. Seems like that tcmalloc really work for some situations.

**Comment by Shellmode** [comment]
Finished last test, which only switch among SDXL models, also little memory leak.

![image](https://github.com/awslabs/stable-diffusion-aws-extension/assets/3354682/0866c617-e66a-4cb3-8723-841376014097)

**Maybe we should not deploy SD1.5 models and SDXL models in one endpoint currently.**

**Comment by yike5460** [comment]
Thanks for the sharing. There mentioned memory leakage fix in 1.6.0 of webui, we will sync upstream in next sprint and should fix the issue.
