### ISSUE TITLE
(Stable Diffusion 亚马逊云科技插件解决方案): (cloudformation模板国内无法下载)

### ISSUE THREAD

**Issue by yaofenglv** [awslabs/stable-diffusion-aws-extension#197]
### Describe the issue

在https://awslabs.github.io/stable-diffusion-aws-extension/zh/deployment/deployment/
中
部署步骤
步骤1：部署Stable Diffusion WebUI (Linux)。
从[链接](https://raw.githubusercontent.com/awslabs/stable-diffusion-aws-extension/main/workshop/ec2.yaml)下载CloudFormation模板。

这个链接需要访问github 国内无法访问，需要更新链接使得国内用户可以访问

### Links

https://raw.githubusercontent.com/awslabs/stable-diffusion-aws-extension/main/workshop/ec2.yaml

**Comment by yike5460** [comment]
Thanks for the feedback, will consider to move to s3 bucket in the future.
