### ISSUE TITLE
CloudFormation: Deploying the solution as a middleware has an error

### ISSUE THREAD

**Issue by sunilopenxyz** [awslabs/stable-diffusion-aws-extension#202]
### Describe the bug

Followed - Step 2: Deploy the solution as a middleware. But AWS CloudFormation Console in the Status column shows ROLLBACK_COMPLETE

In the events tab, the error happens at

`SdDBTrainStackNestedStackSdDBTrainStackNestedStackResource2C42E66E - CREATE_FAILED - Embedded stack arn:aws:cloudformation:us-east-1:215742730356:stack/stable-diffusion-aws-SdDBTrainStackNestedStackSdDBTrainStackNestedStackResource2C42E66-RE0Y9U160BN5/58562390-588c-11ee-9257-0a6f9734f639 was not successfully created: The following resource(s) failed to create: [aigcuploadckptupload2D185426].`

Tried with account that had deployed the middleware before but still getting
`The following resource(s) failed to create: [aigcuploadckptupload2D185426]
`

### Expected Behavior

You can view the status of the stack in the AWS CloudFormation Console in the Status column. You should receive a CREATE_COMPLETE status in approximately 15 minutes.

### Current Behavior

SdDBTrainStackNestedStackSdDBTrainStackNestedStackResource2C42E66E - CREATE_FAILED - Embedded stack arn:aws:cloudformation:us-east-1:215742730356:stack/stable-diffusion-aws-SdDBTrainStackNestedStackSdDBTrainStackNestedStackResource2C42E66-RE0Y9U160BN5/58562390-588c-11ee-9257-0a6f9734f639 was not successfully created: The following resource(s) failed to create: [aigcuploadckptupload2D185426].

### Reproduction Steps

Follow Step 1 and 2 and the error happens in step 2

https://awslabs.github.io/stable-diffusion-aws-extension/en/deployment/deployment/

### Solution Version

0

### AWS Region. e.g., us-east-1

us-east-1

**Comment by sunilopenxyz** [comment]
This is the error that the aigc-upload-ckpt-upload-checkpoint function is running into which causes the above error

`Resource handler returned message: "'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008 (Service: Lambda, Status Code: 400, Request ID: 4819f536-b585-441e-a9e7-a26001bee4b1)" (RequestToken: 16d77ddb-6c9d-c6df-8614-a999a762c013, HandlerErrorCode: InvalidRequest)`

**Comment by yike5460** [comment]
The initial memory size of lambda was 3GB, please consider to raise the limit, e.g 10240 MB.
