### ISSUE TITLE
Environment-Preconfiguration: Use one click AWS CloudFormation Template to install EC2 instance with WebUI error

### ISSUE THREAD

**Issue by wpr7280** [awslabs/stable-diffusion-aws-extension#39]
### Describe the bug

errorMsg: 

`
$ cat webui-log.txt

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on ubuntu user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
ERROR: Cannot activate python venv, aborting...
################################################################`

### Expected Behavior

Stable Diffusion WebUI start ok.

### Current Behavior

According to ec2.yaml file, it will execute command: 
```
            #!/bin/bash
            sudo sed -i "/#\$nrconf{restart} = 'i';/s/.*/\$nrconf{restart} = 'a';/" /etc/needrestart/needrestart.conf
            sudo apt-get update
            sudo apt install wget git python3 python3.8-venv build-essential net-tools libgl1 -y
            cd /home/ubuntu
            git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git
            cd stable-diffusion-webui/extensions
            git clone https://github.com/awslabs/stable-diffusion-aws-extension.git
            cd stable-diffusion-aws-extension/
            ./pre-flight.sh -s
            cd ..
            sudo chown -R ubuntu:ubuntu stable-diffusion-aws-extension/ sd_dreambooth_extension/ sd-webui-controlnet/ ../../stable-diffusion-webui/
            cd ..
            sudo -u ubuntu python3 -m venv venv
            sudo -u ubuntu nohup bash webui.sh --enable-insecure-extension-access --skip-torch-cuda-test --no-half --listen > webui-log.txt
```

webui-log.txt errorMsg:

 ################################################################
ERROR: Cannot activate python venv, aborting...
################################################################`

### Reproduction Steps

Use CloudFormation deploy ec2.yaml 
region: ap-northeast-1

### Solution Version

SO8032

### AWS Region. e.g., us-east-1

ap-northeast-1

**Comment by yike5460** [comment]
Thanks for your feedback, we are not able to re-produce the issue, would you please provide more details on the operation?We just tried again and the address from CloudFormation output can be launched as expected (ap-northeast-1), the output of webui-log is shown below:
ubuntu@ip-172-31-23-22:~/stable-diffusion-webui$ cat webui-log.txt 

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on ubuntu user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Cannot locate TCMalloc (improves CPU memory usage)
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Collecting torch==2.0.1
  Downloading https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp38-cp38-linux_x86_64.whl (2267.3 MB)
Collecting torchvision==0.15.2
  Downloading https://download.pytorch.org/whl/cu118/torchvision-0.15.2%2Bcu118-cp38-cp38-linux_x86_64.whl (33.9 MB)
Collecting triton==2.0.0; platform_system == "Linux" and platform_machine == "x86_64"
  Downloading triton-2.0.0-1-cp38-cp38-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (63.2 MB)
Collecting typing-extensions
  Downloading typing_extensions-4.7.0-py3-none-any.whl (33 kB)
Collecting sympy
  Downloading sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting filelock
  Downloading filelock-3.12.2-py3-none-any.whl (10 kB)
Collecting jinja2
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting networkx
  Downloading networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting numpy
  Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Collecting requests
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
Collecting pillow!=8.3.*,>=5.3.0
  Downloading Pillow-9.5.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Collecting lit
  Downloading lit-16.0.6.tar.gz (153 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting cmake
  Downloading cmake-3.26.4-py2.py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (24.0 MB)
Collecting mpmath>=0.19
  Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (195 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.0.3-py3-none-any.whl (123 kB)
Building wheels for collected packages: lit
  Building wheel for lit (PEP 517): started
  Building wheel for lit (PEP 517): finished with status 'done'
  Created wheel for lit: filename=lit-16.0.6-py3-none-any.whl size=93582 sha256=1beedf900d36b8227e1c6f4a4cb6498a29ef70c3b575bc9361f1d14f32531f62
  Stored in directory: /home/ubuntu/.cache/pip/wheels/05/ab/f1/0102fea49a41c753f0e79a1a4012417d5d7ef0f93224694472
Successfully built lit
Installing collected packages: filelock, lit, cmake, triton, typing-extensions, mpmath, sympy, MarkupSafe, jinja2, networkx, torch, numpy, charset-normalizer, idna, certifi, urllib3, requests, pillow, torchvision
Successfully installed MarkupSafe-2.1.3 certifi-2023.5.7 charset-normalizer-3.1.0 cmake-3.26.4 filelock-3.12.2 idna-3.4 jinja2-3.1.2 lit-16.0.6 mpmath-1.3.0 networkx-3.1 numpy-1.24.4 pillow-9.5.0 requests-2.31.0 sympy-1.12 torch-2.0.1+cu118 torchvision-0.15.2+cu118 triton-2.0.0 typing-extensions-4.7.0 urllib3-2.0.3
