### ISSUE TITLE
Have the Generate on Cloud button automatically display the generated images when generation is complete

### ISSUE THREAD

**Issue by AGronowski** [awslabs/stable-diffusion-aws-extension#41]
### Describe the feature

Is there some way to have the generated images automatically show up as soon as the generation succeeds? And for the progress bar to work?

### Use Case

This would make the user experience much better as it would eliminate steps and make the process faster and easier

### Proposed Solution
Ideally clicking the generate on cloud button would result in identical behavior to clicking the regular generate button. I'm not sure how difficult this would be to implement but would be great if possible.

### Solution version used

 v1.3.2

**Comment by yike5460** [comment]
Thanks for the feedback. We already support the auto refresh for inference result in dec branch and will official release to main branch in v1.0.1

**Comment by AnyISalIn** [comment]
https://github.com/omniinfer/sd-webui-cloud-inference

I have created a similar extensions inspired by aws extension to solve the problems, its ensuring compatibility with stable diffusion webui is main goal.

**Comment by hvmiao** [comment]
> https://github.com/omniinfer/sd-webui-cloud-inference
> 
> I have created a similar extensions inspired by aws extension to solve the problems, its ensuring compatibility with stable diffusion webui is the main goal.



> https://github.com/omniinfer/sd-webui-cloud-inference
> 
> I have created a similar extensions inspired by aws extension to solve the problems, its ensuring compatibility with stable diffusion webui is the main goal.

Looks good, I'll give a try. thx anyway.

**Comment by yike5460** [comment]
@AGronowski feature resolved in new release v1.0.1, closed for now.
