### ISSUE TITLE
No User and Role Management Tab

### ISSUE THREAD

**Issue by tan-blng** [awslabs/stable-diffusion-aws-extension#478]
### Describe the issue

Followed the documentation, and deploy all the stacks (stable-diffusion-webui and extension, and the middleware) successfully. However, there is no "role management" or "user management" tab under the "AWS SageMaker" tab. It asks for API URL and API Token, as well as Username and Password. I filled in API URL and API Token, which is copied from middleware stack output, but not sure what about username and password. I tried leave it empty, and also guessed with "admin", and then click the "Test Connection & Udpate Setting" button, the result is always "Failed to connect to backend server, please check the url and token" in the label area. The log reports: 

DEBUG:aws_extension.sagemaker_ui_tab:user None logged in
ERROR:aws_extension.sagemaker_ui_tab:Error: Failed to get server request. Details: 403 Client Error: Forbidden for url: https://{xxxxxxxxxx}.execute-api.us-west-2.amazonaws.com/prod/ping

I checked webui version, which is 1.7.0, and other extensions version (e.g. ControlNet) all compatible. 
I also tried the file sagemaker_ui.json, filled in the api_gateway_url and api_token value, and leave the "username" empty, but didn't work. 

Thank you for helping looking into this issue.

![image](https://github.com/awslabs/stable-diffusion-aws-extension/assets/135720662/4883c4ad-e9d5-4e09-8384-51be2a5a091a)

### Links

https://awslabs.github.io/stable-diffusion-aws-extension/en/user-guide/multi-user/

**Comment by elonniu** [comment]
May I ask if you were within 10 minutes of successful deployment when you encountered this error? If so, please try again.

**Comment by tan-blng** [comment]
Thanks, problem solved by using the 1.4.0 cloudformation template.
