### ISSUE TITLE
API document outdated

### ISSUE THREAD

**Issue by tan-blng** [awslabs/stable-diffusion-aws-extension#483]
### Describe the issue

The API document is very useful to guide direct API call, however seems outdated for a while. It would be very helpful to update it, especially the important /inferences section. Or is there any code we can reference for the detail? 

Thank you again for helping looking into this. Really appreciate the amazing work here. 

### Links

https://github.com/awslabs/stable-diffusion-aws-extension/blob/main/docs/en/developer-guide/api.md

**Comment by NingLu** [comment]
We are working on the API doc, here're some examples in terms of inference

https://github.com/elonniu/esd-api-examples/tree/main

**Comment by tan-blng** [comment]
Thanks a lot. It works like a charm!
