### ISSUE TITLE
Generating success, but image didn't loaded

### ISSUE THREAD

**Issue by bimanata** [awslabs/stable-diffusion-aws-extension#490]
### Describe the bug

During image generation on cloud, I noticing that after doing generation several times (usually after 15-20 tries), the UI somehow looks unresponsive. The button Generate on Cloud didn't appear and it still show "Interrupt | Skip" button. 
After checking furthers, seems the image generation is success. I know it because when I check on Inference Job histories, there was success result. And if I click that history, the image actually appear.

But if I continue to click generate on cloud, it keeps showing the same like above. The only way I can generate image again is by restarting the sd-webui.service. Then after that, I'm able to generate again. But the issue appear again after I generate 15-20 images

### Expected Behavior

After click Generate on Cloud -> Inference Job started -> Image generated and shown in the UI

repeat, I can do this all the time to ensure Stable Diffusion generate the image that I want / expected

### Current Behavior

After click Generate on Cloud -> Inference Job started -> from UI perspective looks like the UI is stuck and keep showing the "Interrupt | Skip" and didn't show the image generation result

### Reproduction Steps

1. Generating 15 - 20 images using Generate on Cloud
2. Change prompt / adjust config , then Generate on Cloud 
3. The UI shown it looks like generating
4. but after sometimes, the UI still looks like generating image and looks never finish
5. after refresh and check inference job history, there is actually result in the time I click the Generate on Cloud button.. and if I open the history actually it successfully generating image and the image shown on the UI
6. I try to click Generate on Cloud again, but the result still the same like on step 3 to 4

### Additional Information/Context

Testing using only 1 user and 1 tab.
and looking at log, looks like there is no error happening

### Solution Version

v1.4.0-1a63244

### AWS Region. e.g., us-east-1

ap-southeast-1

### Other information

Automatic1111 version: 1.7.0
Automatic1111 host: EC2
EC2 Instance type: g4dn.xlarge
Sagemaker Endpoint instance type: g4dn.2xlarge (1 instance)

**Comment by elonniu** [comment]
Is the WebUI in the same region as the API? You can try refreshing or restarting the WebUI.

**Comment by bimanata** [comment]
hi @elonniu yes, both webui and the extension are deployed in ap-southeast-1

Tried already to refresh the page, but it still persist. The only way the image loaded again after generation is by restarting the WEBUI service inside the EC2

**Comment by elonniu** [comment]
How can I contact you?
