### ISSUE TITLE
majority: WebUI crashed after install the extension

### ISSUE THREAD

**Issue by yourlin** [awslabs/stable-diffusion-aws-extension#51]
### Describe the bug

WebUI crashed after install the extension
After deleting the extension, WebUI can work fine.

### Expected Behavior

WebUI can work fine.

### Current Behavior

WebUI crashed

### Reproduction Steps

- Install the extension 
- Apply and Reload UI
- Crashed

### Additional Information/Context

- version: [v1.3.2](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/baf6946e06249c5af9851c60171692c44ef633e0) 
- python: 3.8.10 
- torch: 2.0.1+cu118
- xformers: N/A
- gradio: 3.32.0
- checkpoint: [ac68270450]

### Solution Version

v1.0.0

### AWS Region. e.g., us-east-1

us-east-1

**Comment by alvindaiyan** [comment]
Thanks for your feedback. Can you provide crash logs?
