### ISSUE TITLE
Additional Extensions : After webui cloudformation+middleware configuration, installing additional extensions causing crashes

### ISSUE THREAD

**Issue by jazst21** [awslabs/stable-diffusion-aws-extension#635]
### Describe the bug

After install webui client using prebuilt image from [link](https://github.com/awslabs/stable-diffusion-aws-extension/blob/main/docs/Environment-Preconfiguration.md) cloudformation template provided, and configure extension middle ware backend, the webui keep having crashes when installing new additional extensions from using the extension tab. extension tested which causes crashes = Ultimate SD Upscale and Infinite Image Browser. attached crash log

### Expected Behavior

After install webui client using prebuilt image from [link](https://github.com/awslabs/stable-diffusion-aws-extension/blob/main/docs/Environment-Preconfiguration.md) cloudformation template provided, and configure extension middle ware backend, the webui need to be able to keep installing new extensions without issues

### Current Behavior

After install webui client using prebuilt image from [link](https://github.com/awslabs/stable-diffusion-aws-extension/blob/main/docs/Environment-Preconfiguration.md) cloudformation template provided, and configure extension middle ware backend, the webui keep having crashes when installing new additional extensions from using the extension tab. extension tested which causes crashes = Ultimate SD Upscale and Infinite Image Browser. attached crash log

### Reproduction Steps

1. install webui client using prebuilt image from [link](https://github.com/awslabs/stable-diffusion-aws-extension/blob/main/docs/Environment-Preconfiguration.md) cloudformation template provided
2. install webui-extension middleware using [link](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?stackName=SdWebUiMidWare&templateURL=https://aws-gcr-solutions.s3.amazonaws.com/stable-diffusion-aws-extension-github-mainline/latest/custom-domain/Extension-for-Stable-Diffusion-on-AWS.template.json) cloudformation template provided.
3. restart webui using webui button
4. configure extension middle ware backend with api gateway, key, username, password
5. restart webui, login with username/password
6. install new webui extension using extension browser : Ultimate SD Upscale and Infinite Image Browser
7. journalctl -u sd-webui -f, look for crashes logs. webui not functioning normal,"error" label messages on ui. attached [log.log](https://github.com/awslabs/stable-diffusion-aws-extension/files/14814394/log.log)
8. rm -rf new installed extensions
9. sudo systemctl restart sd-webui
10. webui running normal again

### Additional Information/Context

1. ec2 instance type for deploying webui = c5.4xlarge. this crash behavior consistent with installing other extensions.
2. attached crash log observed using `journalctl -u sd-webui -f`
[log.log](https://github.com/awslabs/stable-diffusion-aws-extension/files/14814391/log.log)

### Solution Version

Description: (SO8032) - Extension for Stable Diffusion on AWS - EC2 Instance

### AWS Region. e.g., us-east-1

us-east-1

**Comment by jazst21** [comment]
tried to install extensions manually using cd /extensions, git clone, and restart service. webui,middleware and new extension working fine.

**Comment by elonniu** [comment]
Some extensions may cause abnormal webui due to defects. We suggest that if you encounter problems, you can delete the plugins and restart webui.
