### ISSUE TITLE
webui reload ui button result in application crash

### ISSUE THREAD

**Issue by jazst21** [awslabs/stable-diffusion-aws-extension#682]
### Describe the bug

1. started webui normally
2. login user/password created through the aws extension
3. click reload ui button on the home page footer
4. "journalctl -u sd-webui -f", command shows error messages
5. refresh the web ui web page and login
6. "journalctl -u sd-webui -f", keep showing error messages
7. web ui does not responding correctly and shows error messages on web page. non-functioning on inference/other action.
8. do a manual "sudo systemctl restart sd-webui".
9. web page reloaded, log in, web ui back to normal behaviour
in summary, the webui reload ui button become non-functioning (*bug) on installation of aws-extension. this does not happen on standard sd webui without aws extension.
log attached 
[error reload.log](https://github.com/awslabs/stable-diffusion-aws-extension/files/15002586/error.reload.log)

### Expected Behavior

reload ui web button works normal. 
journalctl -u sd-webui -f should shown normal service reload.
no error message on web app after reload-login

### Current Behavior

1. started webui normally
2. login user/password created through the aws extension
3. click reload ui button on the home page footer
4. "journalctl -u sd-webui -f", command shows error messages
5. refresh the web ui web page and login
6. "journalctl -u sd-webui -f", keep showing error messages
7. web ui does not responding correctly and shows error messages on web page. non-functioning on inference/other action.
8. do a manual "sudo systemctl restart sd-webui".
9. web page reloaded, log in, web ui back to normal behaviour
in summary, the webui reload ui button become non-functioning (*bug) on installation of aws-extension. this does not happen on standard sd webui without aws extension.

### Reproduction Steps

1. started webui normally
2. login user/password created through the aws extension
3. click reload ui button on the home page footer
4. "journalctl -u sd-webui -f", command shows error messages
5. refresh the web ui web page and login
6. "journalctl -u sd-webui -f", keep showing error messages
7. web ui does not responding correctly and shows error messages on web page. non-functioning on inference/other action.
8. do a manual "sudo systemctl restart sd-webui".
9. web page reloaded, log in, web ui back to normal behaviour
in summary, the webui reload ui button become non-functioning (*bug) on installation of aws-extension. this does not happen on standard sd webui without aws extension.

### Possible Solution

patch the webui reload button code to trigger the sd-webui background service reload instead of only reloading webui.py

### Solution Version

Description: (SO8032) - Extension for Stable Diffusion on AWS - EC2 Instance

### AWS Region. e.g., us-east-1

us-east-1

### Other information

log attached
[error reload.log](https://github.com/awslabs/stable-diffusion-aws-extension/files/15002550/error.reload.log)

**Comment by jazst21** [comment]
on source code 
html/footer.html:
<a href="/" onclick="javascript:gradioApp().getElementById('settings_restart_gradio').click(); return false">Reload UI</a>
-----
on modules/ui_settings.py:
            restart_gradio.click(
                fn=shared.state.request_restart,
                _js='restart_reload',
                inputs=[],
                outputs=[],
            )
-----
on modules/shared_state.py:
    def request_restart(self) -> None:
        self.interrupt()
        self.server_command = "restart"
        log.info("Received restart request")
-----
this might be a good place to start changing the code into restarting web-ui background service command.

**Comment by jazst21** [comment]
i did some change on the source code. the bug resolved.
on modules/shared_state.py:
```
import os
def request_restart(self) -> None:
    self.interrupt()
    #self.server_command = "restart"
    os.system('sudo systemctl restart sd-webui')
    log.info("Received restart request")
```

**Comment by elonniu** [comment]
Thanks feedback, we will deal with this.
