### ISSUE TITLE
CloudFormation template ec2.yaml fails to properly install Stable Diffusion Web UI on EC2

### ISSUE THREAD

**Issue by keykbd** [awslabs/stable-diffusion-aws-extension#705]
### Describe the bug

When using ec2.yaml to set up a Stable Diffusion Web UI environment, the CloudFormation stack is successfully built, but there seems to be some issue during the installation of Stable Diffusion Web UI on the EC2 instance.
https://github.com/awslabs/stable-diffusion-aws-extension/blob/main/workshop/ec2.yaml

### Expected Behavior

The expected outcome is to be able to use the Stable Diffusion Web UI after the CloudFormation deployment is complete.

### Current Behavior

Even after waiting for about 30 minutes after the CloudFormation deployment is finished and accessing the Web UI, the message "WebUI is Initializing or Starting" is still displayed.

### Reproduction Steps

This issue is reproducible regardless of the region when deploying using the ec2.yaml template.

### Solution Version

SO8032

### AWS Region. e.g., us-east-1

us-east-1, us-west-2, ap-northeast-1

**Comment by elonniu** [comment]
Suggest waiting for a longer time

**Comment by keykbd** [comment]
The situation remained unchanged even after waiting for 24 hours. I tried several more times, but the process seemed to end at the point of executing `s5cmd -d run sd_models.txt`, and it appeared that sd-webui.service was not being created. This issue persists even when using a different AWS account.

Manually running `s5cmd -d run sd_models.txt` and creating sd-webui.service does work, but it's inconvenient.

**Comment by keykbd** [comment]
I apologize for the confusion. I tried running the code with a different AWS account, and it executed without any issues.
It seems that the problem was with my environment.
