### ISSUE TITLE
controlnet: not work on sagemaker inference

### ISSUE THREAD

**Issue by kazuhitogo** [awslabs/stable-diffusion-aws-extension#778]
### Describe the bug

I have deployed following this procedure.
https://awslabs.github.io/stable-diffusion-aws-extension/ja/deployment/deployment/

I have added controlnet from SageMaker tab
e.g.
https://huggingface.co/lllyasviel/ControlNet-v1-1/blob/main/control_v11p_sd15_openpose.pth
https://huggingface.co/cagliostrolab/animagine-xl-3.1/blob/main/animagine-xl-3.1.safetensors
https://huggingface.co/lllyasviel/control_v11p_sd15_openpose/blob/main/diffusion_pytorch_model.safetensors

and Generate image on SageMaker but not work controlnet
<img width="1868" alt="image" src="https://github.com/awslabs/stable-diffusion-aws-extension/assets/7238979/9de7a9d2-0ffd-4556-927b-02e5c9a25ed1">

### Expected Behavior

I expect controlnet working well
on local is good
<img width="1893" alt="image" src="https://github.com/awslabs/stable-diffusion-aws-extension/assets/7238979/6881755d-727d-41ea-9d87-8e3d862440f6">

### Current Behavior

Controlnet is not working.

### Reproduction Steps

on GUI

### Additional Information/Context

Cloudwatch Log (SageMaker async inference) 
```plain
*** Error running process: /home/ubuntu/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py Traceback (most recent call last): File "/home/ubuntu/stable-diffusion-webui/modules/scripts.py", line 784, in process script.process(p, *script_args) File "/home/ubuntu/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1279, in process self.controlnet_hack(p) File "/home/ubuntu/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1264, in controlnet_hack self.controlnet_main_entry(p) File "/home/ubuntu/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 936, in controlnet_main_entry model_net, control_model_type = Script.load_control_model(p, unet, unit.model) File "/home/ubuntu/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 367, in load_control_model control_model = Script.build_control_model(p, unet, model) File "/home/ubuntu/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 385, in build_control_model raise RuntimeError(f"model not found: {model}") RuntimeError: model not found: None
```

### Solution Version

version: v1.8.0  •  python: 3.10.12  •  torch: 2.0.1+cu118  •  xformers: N/A  •  gradio: 3.41.2  •  checkpoint: 05371826b5

### AWS Region. e.g., us-east-1

us-east-1 and ap-northeast-1

**Comment by HappyXY** [comment]
thanks for your question~
There may be two reasons:
1) please make sure the controlnet model has been uploaded to s3 through the model management tab
2) in the txt2img tab, select the inference job in the inference job list and click the API, the parameters for this job will be shown in a new tab. Please upload the log information here
