### ISSUE TITLE
(module name): (short issue description)

### ISSUE THREAD

**Issue by odinwang** [awslabs/stable-diffusion-aws-extension#88]
### Describe the feature

Since we will have multiple checkpoint model and ControlNet models, upload them one by one is not efficient. Suggest can let user upload the models to S3 directly.

### Use Case

Upload models one by one is not efficient.

### Proposed Solution

Suggest can let user upload the models to S3 directly.

### Solution version used

d016b447

**Comment by yike5460** [comment]
Thanks for the feedback, feature already on roadmap, closed for now.
