### ISSUE TITLE
Training status is stuck at "Initial", the training job on SageMaker did not be created

### ISSUE THREAD

**Issue by eric80116** [awslabs/stable-diffusion-aws-extension#89]
### Describe the bug

Hi,

I installed middleware **ecrimagetag：v1.0.0-8a4864f** and follow the steps of this [documentation](https://awslabs.github.io/stable-diffusion-aws-extension/zh/user-guide/dreambooth-guide/)
1/ Create model from cloud
2/ Select model from cloud
3/ Config Input module including the following
* Use LORA
* Type Dataset Directory
* Type Instance Prompt under Training Prompt
* Check "Save Checkpoint to Subdirectory"
* Leave "Generate lora weights for extra networks" uncheck 
* Click "SageMaker Train"

Then, the Training Jobs Details show the status "Initial" on the buttom-left but did not see the training job be created on SageMaker console.

### Expected Behavior

The training job should be created or any error message pop up for checking

### Current Behavior

<img width="1039" alt="Screenshot 2023-07-16 at 9 09 45 AM" src="https://github.com/awslabs/stable-diffusion-aws-extension/assets/28819360/4f3b1979-65cf-43d8-b6f5-5b4902d08716">
<img width="428" alt="Screenshot 2023-07-16 at 9 09 39 AM" src="https://github.com/awslabs/stable-diffusion-aws-extension/assets/28819360/3746e7c0-5a91-4ad6-b85c-36bf568e1626">

### Reproduction Steps

Just following the [documentation](https://awslabs.github.io/stable-diffusion-aws-extension/zh/user-guide/dreambooth-guide/) step by step

### Solution Version

webui-extension-commit: 4c1615ccc280c1cea515f58027379408469b4ddc 
middleware ecrimagetag: v1.0.0-8a4864f

### AWS Region. e.g., us-east-1

us-east-1

**Comment by alvindaiyan** [comment]
when the status turns to "Training", a training job will be created but not when "Initial". What os you are using for you sd web ui?

**Comment by eric80116** [comment]
ubuntu, I used the [ec2 template](https://raw.githubusercontent.com/awslabs/stable-diffusion-aws-extension/main/workshop/ec2.yaml) to build the webui server. 
Also, my training job stuck at 'Initial' state longer than 1 hour, so something probably went wrong. Any idea which log group can check the error message for this issue?

**Comment by alvindaiyan** [comment]
I suspect the process is stuck at the webui process, I suggest you go to your ec2 server and find out the log of your webui

**Comment by alvindaiyan** [comment]
> ubuntu, I used the [ec2 template](https://raw.githubusercontent.com/awslabs/stable-diffusion-aws-extension/main/workshop/ec2.yaml) to build the webui server. Also, my training job stuck at 'Initial' state longer than 1 hour, so something probably went wrong. Any idea which log group can check the error message for this issue?

To get the ec2 log, you can go to the console and connect to the ec2 use the web console. The command you can use to get the log is : ``` journalctl -u sd-webui.service -b -f ``` (only if you deployed the webui use the latest ec2.yaml template)

**Comment by eric80116** [comment]
I start recording the log when I did the following steps 
1. Upload the dataset (by AWS Dataset Management)
2. Create model from cloud
3. Select model from cloud
4  SageMaker training

The log did not show after the step of uploading the data, even the step of Creating model is successful.


![Screenshot 2023-07-17 at 9 31 18 AM](https://github.com/awslabs/stable-diffusion-aws-extension/assets/28819360/9491d8a4-f522-4bc9-ac79-5ca35b139036)
![Screenshot 2023-07-17 at 9 29 02 AM](https://github.com/awslabs/stable-diffusion-aws-extension/assets/28819360/fa1db41e-cd3d-4e63-a6f8-f2921a58734b)
![Screenshot 2023-07-17 at 9 23 03 AM](https://github.com/awslabs/stable-diffusion-aws-extension/assets/28819360/b86bebe6-ab60-4322-ac7e-e36d3e63f475)

**Comment by eric80116** [comment]
I start recording the log when I did the following steps

1.Upload the dataset (by AWS Dataset Management)
2.Create model from cloud
3.Select model from cloud
4.SageMaker training
The log did not show after the step of uploading the data, even the step of Creating model is successful.

![Screenshot 2023-07-17 at 9 23 03 AM](https://github.com/awslabs/stable-diffusion-aws-extension/assets/28819360/2322c1f4-101e-49d9-b275-05ca922e4d08)
![Screenshot 2023-07-17 at 9 29 02 AM](htt
![Screenshot 2023-07-17 at 9 31 18 AM](https://github.com/awslabs/stable-diffusion-aws-extension/assets/28819360/3334dd95-683c-4e4c-873a-87de764b0bb9)
ps://github.com/awslabs/stable-diffusion-aws-extension/assets/28819360/b2acc6d7-0342-4758-a4be-1924745ab5fe)

**Comment by eric80116** [comment]
Thanks for help. 
Problem solved, since the service quota for SageMaker training job is not enough, the the training job cannot be created successfully. But the job status did not change to "Fail" is still a issue.

**Comment by yike5460** [comment]
Thanks for your feedback, closed for now
