### ISSUE TITLE
img2img inference config not match the request

### ISSUE THREAD

**Issue by eric80116** [awslabs/stable-diffusion-aws-extension#90]
### Describe the bug

When I tried to generate the image on cloud, the model in the inference config is different with what I config
For example, I config to use yangk-style model, but it inference another model to generate the image

![Screenshot 2023-07-17 at 9 42 35 AM](https://github.com/awslabs/stable-diffusion-aws-extension/assets/28819360/779ef5d5-9fc4-4442-8129-ccfb7203a095)

![Screenshot 2023-07-17 at 9 43 07 AM](https://github.com/awslabs/stable-diffusion-aws-extension/assets/28819360/051c4535-a639-4b73-a7ac-0f77c611db41)

### Expected Behavior

The model for inferencing use should be the same model with what I config.

### Current Behavior

the model in the inference config is different with what I config

### Reproduction Steps

Choose img2img then do the inference. 

### Solution Version

v1.0.0-8a4864f

**Comment by yike5460** [comment]
Thanks for you feedback, we are investigating the issue.
